version: "3.8"

services:
  db:
    image: postgres:15.1
    hostname: db
    container_name: asap_form_db
    restart: always
    ports:
      - 5555:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=emmy1234
      - POSTGRES_DB=database
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
    cap_add:
      - SYS_NICE
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "database"]
      interval: 10s
      timeout: 5s
      retries: 5
